### ISSUE TITLE
UnhandledPromiseRejectionWarning when yarn/npm start

### ISSUE THREAD

**Issue by Michielnuyts** [learnapollo/pokedex-react#10]
`yarn start v0.21.3
$ react-scripts start 
(node:42570) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: "listener" argument must be a function
(node:42570) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 1.73s.`

##Hello,

I get this error when installing ANY of the exercises or solutions, they all give me the same error.

Thanks!

**Comment by marktani** [comment]
Hey, looks like you need to downgrade your `node` version to 7.7.1. See https://github.com/facebookincubator/create-react-app/issues/1776.
