### ISSUE TITLE
Promise rejections upon starting first exercise

### ISSUE THREAD

**Issue by lxm7** [learnapollo/pokedex-react#9]
After running `yarn start # or npm start` on excercise-01, I receive warning:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: "listener" argument must be a function
(node:21712) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.
```

I did a brew update today and currently on node@7.7.2 and npm@4.1.2. Not sure if theres a breaking change there?

Im also getting, running `npm i`

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp)

Also tried other folders from repo also with same issue.

**Comment by marktani** [comment]
This is related to the very fresh bug regarding node@7.7.2 and create-react-app, more information can be found here: https://github.com/facebookincubator/create-react-app/issues/1776. 

**Solution:** Either upgrade create-react-app to 0.9.5 or downgrade node to 7.7.1 or older.

**Comment by lxm7** [comment]
Ah ok, Thanks!

On Fri, Mar 10, 2017 at 11:32 AM, Nilan Marktanner <notifications@github.com
